Some bugfixes (upscaling, preanimation, webp on char buttons, viewport layout)
AttorneyOnline/webAO pull request #202
Opened 2023-11-22 14:48 UTC by SymphonyVR

This fixes:

- Empty messages don't play the preanimation #191 
- Background scaling #92

Changes:
- Now every image on the viewport is centered on the X and Y axis, so it is more similar to how AO 2.8 manages the viewport by default.
- **Adds support for webp buttons:** It was the only place that didn't have webp support.
- **Better upscaling/downscaling detection.** It gives pixelated/fast to every **gif** and **apng**, while the **png** and **webp** has the smooth filter.

2023-11-22 16:23 UTC, stonedDiscord requested changes
remove the extra top: and we can merge it

2023-11-22 16:23 UTC, stonedDiscord commented on webAO/styles/client.css
>  	top: 0;
please remove the old `top`

2023-11-22 16:23 UTC, stonedDiscord commented on webAO/styles/client.css
> +    transform: translate(-50%, -50%);
this is a known trick to center stuff in css but it doesn't work in all situations, need to test this

2023-11-22 16:23 UTC, stonedDiscord commented on webAO/styles/client.css
> +	height: 100%;
some benches are only a picture of the bench and this way they would stretch the entire height of the viewport and block it

2023-11-22 16:25 UTC, stonedDiscord commented
i'm willing to go for it with the benches, people should keep their content up to date

2023-11-22 16:25 UTC, stonedDiscord commented on webAO/styles/client.css
> +	height: 100%;
![bancodefensa](https://github.com/AttorneyOnline/webAO/assets/10584181/a4ad89b0-a191-4dbe-990b-8bb4452c9dd9)

2023-11-22 16:42 UTC, SymphonyVR commented
Should be ready now, I think.

2023-11-23 00:02 UTC, stonedDiscord approved these changes

2023-11-23 00:03 UTC, merged

2023-11-24 14:18 UTC, SymphonyVR commented
> Did this fix #92 completely or partially?

**Is partially fixed @OmniTroid. See below for more details**

## Bugs as of now:


### Now the image of the character is centered:
![image](https://github.com/AttorneyOnline/webAO/assets/47229536/3e7a240a-150a-48e4-8465-b4557e0bc0a2)

### But the background and desk isn't centered at all on 16:9:
![image](https://github.com/AttorneyOnline/webAO/assets/47229536/cb870ed0-fb64-4e37-9305-42cebc4fc8ac)
Tho that only happens on judge.
In all the other positions the background stretches, minus the desk.

### Compared to AO2 (16:9 judge):
![image](https://github.com/AttorneyOnline/webAO/assets/47229536/6375fc48-8e5f-4154-ab8a-c9b691a2bef1)


### 4:3 (works fine)
![image](https://github.com/AttorneyOnline/webAO/assets/47229536/c77aad04-6d33-4c7b-9c70-5105ad5554f0)


### 16:9
![image](https://github.com/AttorneyOnline/webAO/assets/47229536/2fc6bddc-45fc-4a43-a1ea-33b105833a5d)

### 16:9 (on AO2):
![image](https://github.com/AttorneyOnline/webAO/assets/47229536/94f4f10e-9526-429b-80ab-afc8d8a39c04)

### 4:3 (witness)
![image](https://github.com/AttorneyOnline/webAO/assets/47229536/ed8658a9-351b-4d59-95c4-46cdea28909b)

### 16:9 (witness)
![image](https://github.com/AttorneyOnline/webAO/assets/47229536/4ebe7169-b24b-4c27-b813-35f2687ff2ca)

### 16:9 (AO2 - witness)
![image](https://github.com/AttorneyOnline/webAO/assets/47229536/e9ea1da3-b508-45a2-95d1-104e9dc2c321)

### 4:3 (Prosecution)
![image](https://github.com/AttorneyOnline/webAO/assets/47229536/994e988b-56fe-4c7f-8980-17428f9996c1)

### 16:9 (Prosecution)
![image](https://github.com/AttorneyOnline/webAO/assets/47229536/9e7c55de-819b-45b3-a83f-7b31af2b864c)

### 16:9 (AO2 - Prosecution)
![image](https://github.com/AttorneyOnline/webAO/assets/47229536/2ca82cbd-8e88-4a0a-a571-c9d87228f1bf)


## Expected behaviour (coming from AO2 client):
- Background, Character and desk should be centered and not stretched.

For it to not have blank space on the sides, content creators would need to fill it  (make the background and desk with 16:9 aspect ratio in mind).

If anyone asks the default aspect ratio is 4:3 as of now, making #180 solved (idk when it got resolved).